server:
  port: 57010

spring:
  application:
    name: juhe-zhifubao
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: DEFAULT
        namespace: b36ded08-caa6-408a-9eee-cc50698693be

  freemarker:
    request-context-attribute: rc
